OUT = output
PAGES = pages
BIB = documentRef.bib
TEX = document.tex
PROJ = document

CLEAN_DIRS  = $(OUT) $(PAGES) .

clean : 
# clean up garbage generated by LaTeX Workshop (VS Code)
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.swp         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.aux         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.bbl         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.blg         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.fdb_latexmk )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.fls         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.log         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.out         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.pdf         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.gz          )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.toc         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.glo         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.glsdefs     )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.glsist      )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.ist         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.bcf         )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.run.xml     )
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.dvi         )

cleanpdf :
	@ -$(foreach dir, $(CLEAN_DIRS) , rm -f $(dir)/*.pdf )

pdf :
	cp $(BIB) $(OUT)
	# natbib
	#pdflatex -output-directory $(OUT) $(TEX)
	#-cd $(OUT); bibtex $(PROJ)

	# bibTeX
	pdflatex -output-directory $(OUT) $(TEX)
	-cd $(OUT); biber $(PROJ)

	# this part is the same for either natbib or bibTeX
	cd ..
	-pdflatex -output-directory $(OUT) $(TEX)
	cp $(OUT)/*pdf .

open :
	make pdf
	open $(OUT)/document.pdf
